spring:
  mail:
    host: smtp.gmail.com
    username: lovespringmvc@gmail.com
    password: pqcn iidx dwsw ohin
    port: 465

    protocol: smtp
    debug: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    show-sql: true
  main:
    web-application-type: servlet
  application:
    name: Doeves
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}


cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

logging:
  level:
    root: WARN
    md.brainet.doeves: INFO

  file:
    name: log/doeves.log