name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          cache: maven

      - name: Test with Maven
        run: mvn clean test

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t lovespringmvc/doeves-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push lovespringmvc/doeves-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_SSH }}
          port: 22
          script: |
            docker compose pull
            docker compose up